### ISSUE TITLE
Disconnects while active can destabilize the plugin's state

### ISSUE THREAD

**Issue by MegaScience** [lmcintyre/Housemate#1]
While the plugin was active and in use, I received a 9000X disconnect ti the Title Screen, which caused the UI to empty and be unable to repopulate after reconnecting. Temporarily, this was resolved by disabling and re-enabling the plugin. (Of course restarting the game would likely have resolved it as well.) However, this seemed to make its state unstable, as initialization later in the game session immediately crashed the game client.

The plugin requires management checks for unexpected game state changes.

**Comment by lmcintyre** [comment]
Thanks for this report. This was fixed in 6f9b365.
